variable "hostnames" {}
variable "qty" {}
variable "flavor" {}
variable "os" {}
variable "ssh_id" {}
variable "tags" {}
variable "domain" {}
variable "ssh_key" {}
variable "hostname" {}
variable "datacenter" {}
variable "public_vlan" {}
variable "private_vlan" {}