variable "workers" {}
variable "rh_user" {}
variable "rh_pass" {}
variable "pool_id" {}
variable "ssh_key" {}
variable "installer" {}
variable "cluster_domain" {}
variable "master" {}
variable "lb" {}
variable "wsl_install" {}
variable "wkc_install" {}
variable "wkc_patch" {}
variable "namespace" {}
variable "subnet" {}